# apiVersion: v1
# kind: Service
# metadata:
#   name: react-app-service
# spec:
#   type: NodePort
#   ports:
#     - port: 80
#       targetPort: 3000
#       nodePort: 30000
#   selector:
#     app: react-app



apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  ports:
    - port: 80        # Exposes the app on port 80
      targetPort: 80  # Routes traffic to port 80 in the container
      nodePort: 30000 # Optional: NodePort to access externally
  selector:
    app: react-app
